# Generated by Django 5.1.4 on 2025-07-25 17:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='staff',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 25, 17, 31, 20, 946717, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='courses', to='attendance.staff'),
        ),
    ]
