# Generated by Django 5.1.4 on 2025-07-27 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_student_roll_number_student_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='marked_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='staff',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='Absent', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='time_marked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(),
        ),
    ]
